import os, random, json, subprocess, sys

SHARD_SIZE = 100
MOODS = ["Resting", "Prime", "Burnout", "Wired"]
MOOD_FILES = {m: f"data/{m.lower()}.txt" for m in MOODS}
SHARD_DIR = "resources/quotes"
RESOURCE_XML = "resources/resources.xml"
SHARD_INDEX_MC = "source/Core/ShardIndex.mc"

SEPARATOR = "\n|\n"

def _extract_real_quotes():
    script = os.path.join(os.path.dirname(__file__), "extract_quotes.py")
    if os.path.exists(script):
        print("  [*] Extracting real quotes from database...")
        subprocess.run([sys.executable, script], check=True)

def build_shards_for_mood(mood_name, src_path):
    with open(src_path, "r", encoding="utf-8") as f:
        raw = f.read()
    raw_quotes = raw.split("\0")
    quotes = [q for q in raw_quotes if q.strip()]
    total_quotes = len(quotes)
    num_shards = (total_quotes + SHARD_SIZE - 1) // SHARD_SIZE
    entries = []
    os.makedirs(SHARD_DIR, exist_ok=True)
    for shard_idx in range(num_shards):
        start = shard_idx * SHARD_SIZE
        end = min(start + SHARD_SIZE, total_quotes)
        slice_quotes = quotes[start:end]
        combined = SEPARATOR.join(slice_quotes)
        res_id = f"bin_{mood_name.lower()}_{shard_idx}"
        filename = f"{res_id}.json"
        filepath = os.path.join(SHARD_DIR, filename)
        json_str = json.dumps(combined, ensure_ascii=False)
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(json_str)
        size = len(json_str.encode("utf-8"))
        entries.append((res_id, filename, len(slice_quotes), size))
        print(f"  [+] shard {shard_idx:2d}/{num_shards-1:2d}: {filename} ({len(slice_quotes)} quotes, {size}B)")
    return entries

def generate_resources_xml(all_entries):
    lines = ['<resources>']
    lines.append('    <string id="AppName">Cheerfulness IQ</string>')
    lines.append('    <string id="MenuTitle">Options</string>')
    lines.append('    <string id="NextQuote">Next Quote</string>')
    lines.append('    <string id="SelectMood">Select Mood</string>')
    lines.append('    <string id="MoodWiredLabel">Wired</string>')
    lines.append('    <string id="MoodPrimeLabel">Prime</string>')
    lines.append('    <string id="MoodBurnoutLabel">Burnout</string>')
    lines.append('    <string id="MoodRestingLabel">Resting</string>')
    lines.append('')
    lines.append('    <!-- Quote Shards (JSON strings) -->')
    for res_id, filename, count, size in all_entries:
        lines.append(f'    <jsonData id="{res_id}" filename="quotes/{filename}" />')
    lines.append('')
    lines.append('    <!-- Mood Bitmaps -->')
    for mood in MOODS:
        lines.append(f'    <bitmap id="Mood{mood}" filename="drawables/mood_{mood.lower()}.png" />')
    lines.append('    <bitmap id="LauncherIcon" filename="drawables/launcher_icon.png" />')
    lines.append('</resources>')
    with open(RESOURCE_XML, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"\n[+] Generated {RESOURCE_XML} with {len(all_entries)} shards.")

def generate_shard_index(all_entries):
    mood_shards = {m: [] for m in MOODS}
    for res_id, filename, count, size in all_entries:
        parts = res_id.split("_")
        mood_name = parts[1].capitalize()
        shard_idx = int(parts[2])
        mood_shards[mood_name].append((shard_idx, res_id))

    lines = ['// Auto-generated by build_shards.py -- DO NOT EDIT']
    lines.append('import Toybox.Lang;')
    lines.append('')
    lines.append('module CoreShardIndex {')
    lines.append('')

    max_shards = max(len(v) for v in mood_shards.values())

    lines.append(f'    const SHARD_COUNT as Number = {max_shards};')
    lines.append('')
    lines.append('    const SHARD_IDS as Array = [')
    for mood_idx, mood in enumerate(MOODS):
        shards = sorted(mood_shards[mood], key=lambda x: x[0])
        ids = ', '.join(f'Rez.JsonData.{sid}' for _, sid in shards)
        indent = '        '
        if mood_idx < len(MOODS) - 1:
            lines.append(f'{indent}[{ids}],')
        else:
            lines.append(f'{indent}[{ids}]')
    lines.append('    ];')
    lines.append('}')
    lines.append('')

    with open(SHARD_INDEX_MC, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"[+] Generated {SHARD_INDEX_MC} ({max_shards} shards per mood)")

def main():
    print("=== Cheerfulness IQ Data Pipeline (JSON String Shards) ===")
    _extract_real_quotes()
    all_entries = []
    for mood in MOODS:
        print(f"\nPacking mood: {mood}")
        print(f"  Source: {MOOD_FILES[mood]}")
        entries = build_shards_for_mood(mood, MOOD_FILES[mood])
        all_entries.extend(entries)
    generate_resources_xml(all_entries)
    generate_shard_index(all_entries)
    print("\n=== Done! ===")

if __name__ == "__main__":
    main()
